# Generated by Django 2.2.1 on 2019-11-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('Album_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Album_pic', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_name', models.CharField(max_length=20)),
                ('Singer', models.CharField(max_length=30)),
                ('Song_file', models.FileField(upload_to='media')),
                ('Album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
