# Generated by Django 2.2.1 on 2019-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191102_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='Song_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
